{% set version = "0.5.16" %}
{% set sha = "ce2bd73e3a41176fa29f093e9ad153327a87862430f1b0b121f0cb230c182a6a" %}
{% set python_min = "3.9" %}

package:
    name: usaddress
    version: {{ version }}

source:
    fn: usaddress-{{ version }}-py3-none-any.whl
    url: https://files.pythonhosted.org/packages/b0/4a/ffeb924e9a5d51bdbfff2e2309fb938603dc8bee30b01cd0421e8212c95c/usaddress-{{ version }}-py3-none-any.whl
    sha256: {{ sha }}

build:
    number: 0
    noarch: python
    script: "{{ PYTHON }} -m pip install usaddress-{{ version }}-py3-none-any.whl -vv"

requirements:
    host:
        - python {{ python_min }}.*
        - pip
        - setuptools
    run:
        - python >={{ python_min }}
        - python-crfsuite >=0.7
        - probableparsing

test:
    requires:
        - pip
        - python {{ python_min }}
    imports:
        - usaddress
    commands:
        - pip check

about:
    home: https://github.com/datamade/usaddress
    license: MIT
    license_family: MIT
    license_file: usaddress-{{ version }}.dist-info/licenses/LICENSE
    summary: Parse US addresses using conditional random fields

extra:
    recipe-maintainers:
        - wyseguy7
        - zaneselvans
