{% set version = "0.5.11" %}
{% set sha = "eec4c473b94e2a29350ee335f18bac7fe4fa698e08271211dad5fed63bdd3e60" %}

package:
  name: usaddress
  version: {{ version }}

source:
  fn: usaddress-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/u/usaddress/usaddress-{{ version }}.tar.gz
  sha256: {{ sha }}

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - requests
    - future
    - python-crfsuite
    - probableparsing
    - metaphone

test:
  imports:
    - usaddress

about:
  home: https://github.com/datamade/usaddress
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: Parse US addresses using conditional random fields

extra:
  recipe-maintainers:
    - wyseguy7
