{% set version = "0.5.14" %}
{% set sha = "121d6775979bc8acb51dd1b514b277c716fbe2edbd956f75a208b6363558a403" %}

package:
  name: usaddress
  version: {{ version }}

source:
  fn: usaddress-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/u/usaddress/usaddress-{{ version }}.tar.gz
  sha256: {{ sha }}

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - requests
    - future
    - python-crfsuite
    - probableparsing
    - metaphone

test:
  imports:
    - usaddress

about:
  home: https://github.com/datamade/usaddress
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: Parse US addresses using conditional random fields

extra:
  recipe-maintainers:
    - wyseguy7
