{% set version = "0.5.13" %}
{% set sha = "5cebfb74c8e542c1ce4c0be9fe2843e62d03a31c029fafb5960590c556902876" %}

package:
  name: usaddress
  version: {{ version }}

source:
  fn: usaddress-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/u/usaddress/usaddress-{{ version }}.tar.gz
  sha256: {{ sha }}

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - requests
    - future
    - python-crfsuite
    - probableparsing
    - metaphone

test:
  imports:
    - usaddress

about:
  home: https://github.com/datamade/usaddress
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: Parse US addresses using conditional random fields

extra:
  recipe-maintainers:
    - wyseguy7
