{% set version = "0.5.10" %}
{% set sha =  "1a8ebf62d0cce58d7d8286dde70373c530a9317b6fe1752a4197b75b7d0870e3" %}
package:
    name: usaddress
    version: {{ version }}

source:
    fn: usaddress-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/u/usaddress/usaddress-{{ version }}.tar.gz
    sha256: {{ sha }}

build:
    noarch: python
    number: 2
    script: python -m pip install --no-deps --ignore-installed .

requirements:
    build:
        - python
        - setuptools

    run:
        - python
        - requests
        - future
        - python-crfsuite
        - probableparsing
        - metaphone

test:
    imports:
        - usaddress

about:
    home: https://github.com/datamade/usaddress
    license: MIT
    license_family: MIT
    summary: Parse US addresses using conditional random fields

extra:
    recipe-maintainers:
        - wyseguy7
        - ericdill
